version: "3.0"
 
services:
  bot:
    image: bot:1.0.1
    build: ./bot
    command: python bot.py
    volumes:
      - /bot
    env_file:
      - ./.env.bot.dev
  web:
    image: m3_forum:1.0.1
    build: .
    command: gunicorn m3_forum.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/m3_forum
      - static:/staticfiles/
      - media:/mediafiles/
    expose:
      - 8000
    env_file:
    - ./.env.dev
  nginx:
    build: ./nginx
    ports:
      - "80:80"
  #    - "443:443"
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
  #    - ./certbot/www:/var/www/certbot/:ro
  #    - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
  #certbot:
  #  image: certbot/certbot:latest
  #  volumes:
  #    - ./certbot/www/:/var/www/certbot/:rw
  #    - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static:
  media: